// app/js/components/Dashboard/Dashboard.jsx
import Pump from './../Pump/Pump.jsx';
import Monitor from './../Monitor/Monitor.jsx';
import EventLog from './../EventLog/EventLog.jsx';

class Dashboard extends React.Component {
  render() {
    return (
      <div className="dashboard">
        <div className="columns">
          <div className="column">
            <Pump />
          </div>
        </div>
        {/*
        <div className="columns">
          <div className="column">
             <Monitor />
          </div>
        </div>
        <div className="columns">
          <div className="column">
            <EventLog />
          </div>
        </div>*/}
      </div>
    );
  }
}

export default Dashboard;

// app/js/components/Dashboard.vue
<template>
  <div class="dashboard">
    <!--
    <div class="columns">
      <div class="column">
        <Pump />
      </div>
    </div>
    <div class="columns">
      <div class="column">
        <Monitor />
      </div>
    </div>
    <div class="columns">
      <div class="column">
        <EventLog />
      </div>
    </div>-->
  </div>
</template>
<script>
export default {
  components: {},
};
</script>
